services:
  joint-cv:
    container_name: joint-cv
    image: joint-cv:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: 1.0.0
    volumes:
      - .:/app
      - /mnt/d/vcf/:/vcf
    environment:
      - PYTHONUNBUFFERED=1
    command: python /app/src/GenoJoin.py

